
/**
Constructor
Do not call Function in Constructor.
*/
class EmptyView()
{
	super();

	//TODO:edit here

}
extends AView;


function EmptyView*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function EmptyView*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function EmptyView*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
