
/**
Constructor
Do not call Function in Constructor.
*/
class SildeViews()
{
	super();

	//TODO:edit here

}
extends AView;


function SildeViews*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function SildeViews*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function SildeViews*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
