
/**
Constructor
Do not call Function in Constructor.
*/
class SubView4()
{
	super();

	//TODO:edit here

}
extends AView;


function SubView4*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function SubView4*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function SubView4*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
