
/**
Constructor
Do not call Function in Constructor.
*/
class SubView5()
{
	super();

	//TODO:edit here

}
extends AView;


function SubView5*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function SubView5*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function SubView5*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};

function SubView5*onHideBtnClick(comp, info, e)
{

	this.getContainer().close();

};
