
/**
Constructor
Do not call Function in Constructor.
*/
class tabSubview2()
{
	super();

	//TODO:edit here

}
extends AView;


function tabSubview2*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function tabSubview2*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function tabSubview2*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
