
/**
Constructor
Do not call Function in Constructor.
*/
class tabSubview3()
{
	super();

	//TODO:edit here

}
extends AView;


function tabSubview3*init(context, evtListener)
{
	super.init(context, evtListener);

	//TODO:edit here

};

function tabSubview3*onInitDone()
{
	super.onInitDone();

	//TODO:edit here

};

function tabSubview3*onActiveDone(isFirst)
{
	super.onActiveDone(isFirst);

	//TODO:edit here

};
